In [17]:
import numpy as np
import pandas as pd

In [4]:
list =[1,2,3]

In [5]:
numpy_array=np.array(list)

In [6]:
type(numpy_array)

numpy.ndarray

In [7]:
td_list=[[1,2],[3,4],[5,6]]

In [8]:
matrix=np.array(td_list)

In [9]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
matrix.shape

(3, 2)

In [17]:
matrix.all

<function ndarray.all>

In [51]:
arr=[1,2,3,4,5,6,7,8,9,10]

In [52]:
arr = np.array(arr)

In [53]:
odd = True
even = False

In [54]:
ar = []
for i in range(5):
    try:
     ar.append(odd)
     ar.append(even)
    except:
        print(arr)

        
arr[ar]

array([1, 3, 5, 7, 9])

In [55]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [1]:

norm = np.inalg.norm(arrn)
normal_array = an_array/norm.
print(normal_array)

SyntaxError: invalid syntax (<ipython-input-1-7ce4cf0462df>, line 4)

In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(9).reshape(3,3) #first make a 1d array and reshape it into 3 b 3 mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
#creating identity matrix.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.randn(25) #making a array of 25 numbers with normal distribution

array([-0.36959196, -0.22641025, -0.30747345, -0.40460956,  1.17261832,
       -0.08514026, -0.38932902, -0.51377809,  0.77409928, -0.26955294,
        0.53814747, -0.14944459,  0.21113576,  0.54885008, -0.20866652,
       -0.62123873,  0.16715004,  0.7481043 , -0.92172916, -0.55912112,
        1.31185553, -0.17785274, -1.24365798,  1.38170798, -0.40284734])

In [15]:
#product code that i trnsfered to  0,180  might be a series and i can extract info what 0 mwans

In [24]:
a=pd.Series(data=[0,1,2],index=['motor','car','puppy'])

In [25]:
b=pd.Series(data=[0,1,2],index=['motor','car','japa'])

In [26]:
a+b

car      2.0
japa     NaN
motor    0.0
puppy    NaN
dtype: float64

In [33]:
df= pd.DataFrame(data=np.random.randn(5,3),index='A,B,C,B,f'.split(','),columns='A,B,C'.split(','))

In [30]:
mat=np.random.randn(5,4)

In [35]:
df['A']

A    0.308735
B    0.087099
C   -1.562076
B    0.360008
f   -1.237812
Name: A, dtype: float64

In [36]:
df['NEW']=df['A']+df['B']

In [38]:
df

A         B         C       NEW
A  0.308735  0.484699  0.953770  0.793434
B  0.087099  1.096356 -0.695768  1.183455
C -1.562076  2.881410  1.121563  1.319334
B  0.360008 -0.783676 -0.235996 -0.423668
f -1.237812  1.413408 -0.911191  0.175596

In [39]:
df.loc['A'] #ROW BY INDEXNAME

A      0.308735
B      0.484699
C      0.953770
NEW    0.793434
Name: A, dtype: float64

In [40]:
df.iloc[0] #ROW BY INDEX

A      0.308735
B      0.484699
C      0.953770
NEW    0.793434
Name: A, dtype: float64

In [42]:
df[df>0] #gives only numbers that are>0 else are marked NaN not a number

A         B         C       NEW
A  0.308735  0.484699  0.953770  0.793434
B  0.087099  1.096356       NaN  1.183455
C       NaN  2.881410  1.121563  1.319334
B  0.360008       NaN       NaN       NaN
f       NaN  1.413408       NaN  0.175596

In [44]:
df.reset_index() #index will default values 

index         A         B         C       NEW
0     A  0.308735  0.484699  0.953770  0.793434
1     B  0.087099  1.096356 -0.695768  1.183455
2     C -1.562076  2.881410  1.121563  1.319334
3     B  0.360008 -0.783676 -0.235996 -0.423668
4     f -1.237812  1.413408 -0.911191  0.175596

In [45]:
df.set_index('NEW') #SET INDEX WITH ANOTHER COLUMN 

A         B         C
NEW                                    
 0.793434  0.308735  0.484699  0.953770
 1.183455  0.087099  1.096356 -0.695768
 1.319334 -1.562076  2.881410  1.121563
-0.423668  0.360008 -0.783676 -0.235996
 0.175596 -1.237812  1.413408 -0.911191

In [46]:
df.set_index('NEW',inplace= True) #for permenet change

In [47]:
df.describe()

A         B         C
count  5.000000  5.000000  5.000000
mean  -0.408809  1.018440  0.046476
std    0.917761  1.338397  0.938994
min   -1.562076 -0.783676 -0.911191
25%   -1.237812  0.484699 -0.695768
50%    0.087099  1.096356 -0.235996
75%    0.308735  1.413408  0.953770
max    0.360008  2.881410  1.121563

df.groupby('cATEGORICAL COLUMN').AGGREGATE_FUNCTION()
MIN(), MAX(),SUM(),DESCRIBE

In [48]:
#UNIQUE VALUE IN COL
df['A'].unique()

array([ 0.30873509,  0.08709863, -1.56207617,  0.3600077 , -1.23781209])

In [49]:
df['A'].nunique() #number of unique values

5

In [51]:
df['A'].value_counts()

 0.308735    1
-1.237812    1
 0.360008    1
-1.562076    1
 0.087099    1
Name: A, dtype: int64

In [53]:
#df.head() or df.iloc[:5] first five rows
df.iloc[:5]

A         B         C
NEW                                    
 0.793434  0.308735  0.484699  0.953770
 1.183455  0.087099  1.096356 -0.695768
 1.319334 -1.562076  2.881410  1.121563
-0.423668  0.360008 -0.783676 -0.235996
 0.175596 -1.237812  1.413408 -0.911191