In [2]:
pip install torch

     |████████████████████████████████| 147.1 MB 29 kB/s              ��██████████████████████████▎    | 125.2 MB 14.7 MB/s eta 0:00:02
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch
import numpy as np
torch.__version__

'1.10.0'

In [8]:
#convert numpy array to tensor
array = [1,2,3,4,5]
array=np.array(array)


In [9]:
type(array)

numpy.ndarray

In [21]:
tens = torch.from_numpy(array)

In [25]:
#if i chang array it will aslo autoatically change tensor like below cells
array[0]=10


In [26]:
array

array([10,  2,  3,  4,  5])

In [27]:
tens

tensor([10,  2,  3,  4,  5])

In [33]:
#so to get rid of this  use this rather.
ar=np.arange(1,10)
tensor = torch.tensor(ar)


In [34]:
ar[0]=2
ar

array([2, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2= np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
torch.from_numpy(arr2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
torch.as_tensor(arr2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [37]:
#creating tensors from scratch
t = torch.zeros(4,3,dtype=torch.int32)

In [38]:
t

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [42]:
torch.empty(3,2) #allocates mmeory for 3 by 2 tensor

tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -3.6893e+19]])

In [44]:
torch.arange(0,10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [55]:
#torch.linspace(0,2).reshape(5,2)
torch.rand(3,4)
torch.randn(3,4)
torch.randn(4)

tensor([ 0.2996, -0.6253, -0.0909, -1.1847])

In [59]:
import random
x=torch.randint(low=3,high=6,size=(3,4))

In [64]:
v=x.view(6,2)
v

tensor([[4, 3],
        [4, 5],
        [5, 5],
        [5, 5],
        [3, 5],
        [4, 4]])

In [65]:
x[1,1]=34

In [66]:
v

tensor([[ 4,  3],
        [ 4,  5],
        [ 5, 34],
        [ 5,  5],
        [ 3,  5],
        [ 4,  4]])

In [68]:
z=x.view(2,-1) #if you dont know what will be the next shape. put -1 view and reshape are extreemly sam ebut they differ how obj

In [69]:
z

tensor([[ 4,  3,  4,  5,  5, 34],
        [ 5,  5,  3,  5,  4,  4]])

In [78]:
a= torch.arange(4)
b=torch.arange(4)
c=torch.arange(4).reshape(2,2)
d=torch.arange(4).reshape(2,2)

In [74]:
torch.add(a,b)

tensor([[0, 2],
        [4, 6]])

In [75]:
a.mul(b)

tensor([[0, 1],
        [4, 9]])

In [79]:
a.dot(b)

tensor(14)

In [81]:
torch.mm(c,d) #matrix mul

tensor([[ 2,  3],
        [ 6, 11]])

In [82]:
import numpy as np
import torch

In [84]:
np.random.seed(42)
torch.manual_seed(42)

In [88]:
arr = np.random.randint(0,5,6) #random 6 integer from 0 to 5 exclusive

In [89]:
arr

array([4, 2, 4, 4, 1, 2])

In [95]:
tensor=torch.tensor(arr,dtype=torch.int64)

In [97]:
tensor

tensor([4, 2, 4, 4, 1, 2])

In [98]:
tensor.type()

'torch.LongTensor'

In [99]:
x=tensor.reshape(3,2)

In [100]:
x

tensor([[4, 2],
        [4, 4],
        [1, 2]])

In [104]:
x[:,1]

tensor([2, 4, 2])

In [105]:
x[:,1:]

tensor([[2],
        [4],
        [2]])

In [107]:
x**2

tensor([[16,  4],
        [16, 16],
        [ 1,  4]])

In [119]:
y=torch.randint(0,5,size=(2,3))


In [120]:
torch.mm(x,y)

tensor([[16, 10,  4],
        [24, 12,  4],
        [10,  4,  1]])